CREATE DATABASE AkohoDB
GO

USE AkohoDB
GO

CREATE TABLE Race(idRace INT PRIMARY KEY IDENTITY, race VARCHAR(50), prixSakafo FLOAT, prixPoulet FLOAT, puAtody FLOAT);

CREATE TABLE Sakafo(idSakafo INT PRIMARY KEY IDENTITY,semaine INT,idRace INT,poids FLOAT,quantite FLOAT,FOREIGN KEY(idRace) REFERENCES Race(idRace));

CREATE TABLE Lot(id INT PRIMARY KEY IDENTITY,dateLot DATE,nmbAkoho INT,achat FLOAT,idRace INT,age INT,FOREIGN KEY(idRace) REFERENCES Race(idRace));

CREATE TABLE AkohoMaty(idAkoho INT PRIMARY KEY IDENTITY,idLot INT,nmbMaty INT,dateMaty DATE,FOREIGN KEY(idLot) REFERENCES Lot(id));

CREATE TABLE Atody(idAtody INT PRIMARY KEY IDENTITY,idLot INT,nmbAtody INT,dateAtody DATE,type VARCHAR(20),FOREIGN KEY(idLot) REFERENCES Lot(id));

INSERT INTO Race VALUES ('R1',150,3500,700), ('R2',200,1000,500);

INSERT INTO Sakafo VALUES (0,1,150,0), (1,1,30,60), (2,1,40,80), (3,1,50,90);

INSERT INTO Lot VALUES ('2026-01-01',100,5000,1,0), ('2026-01-09',20,0,1,0);